services:
  # PostgreSQL Database
  - type: pserv
    name: workshift-postgres
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.postgres
    envVars:
      - key: POSTGRES_DB
        value: workshift_manager
      - key: POSTGRES_USER
        value: workshift_user
      - key: POSTGRES_PASSWORD
        generateValue: true

  # Backend API Service
  - type: web
    name: workshift-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: workshift-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: workshift-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: workshift-backend
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: workshift-postgres
    databaseName: workshift_manager
    user: workshift_user
    plan: free